Direct2Rep/Models/Campaign.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Direct2Rep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Campaign()
        {
            this.Visitors = new HashSet<Visitor>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<System.DateTime> Creadted_At { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visitor> Visitors { get; set; }
    }
}

Direct2Rep/Models/Company.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Direct2Rep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.Company_SaleRep = new HashSet<Company_SaleRep>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Logo { get; set; }
        public string Website { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> IsActive { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Creadted_At { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company_SaleRep> Company_SaleRep { get; set; }
    }
}

Direct2Rep/Controllers/CompanyController.cs
using Direct2Rep.BL;
using Direct2Rep.Helping_Classes;
using Direct2Rep.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace Direct2Rep.Controllers
{
    public class CompanyController : Controller
    {
        SessionDTO sessiondto = new SessionDTO();

        #region Sales Representatives
        public ActionResult ListSaleRep()
        {
            if (sessiondto.getRole() == 10)
            {
                List<Company_SaleRep> companysalereps = new AdminBL().getCompany_SaleRepList().Where(x => x.IsActive == 1 && x.CompanyId == sessiondto.getId()).ToList();
                ViewBag.companysalerep = companysalereps;
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Auth");
            }
        }

        //Hassan Codes
        //public ActionResult ListSaleRep(string err, string msg)
        //{
        //    if (sessiondto.getRole() != 10)
        //    {
        //        return RedirectToAction("Login", "Auth");
        //    }
        //    ViewBag.Message = msg;
        //    ViewBag.Error = err;
        //    //List<SaleRepresentative> lists = new AdminBL().getSaleRepresentativeList().OrderBy(x => x.Creadted_At).ToList();
        //    List<Company_SaleRep> lists = new AdminBL().getCompany_SaleRepList().OrderBy(x => x.Creadted_At).ToList();

        //    //List<SaleRepresentative> co_rp_list = new List<SaleRepresentative>();
        //    List<Company_SaleRep> co_rp_list = new List<Company_SaleRep>();

        //    string str = "";
        //    foreach (Company_SaleRep x in lists)
        //    {
        //        if (x.SaleRepresentative.LogoUpload != null && x.SaleRepresentative.PictureUpload == null)
        //        {
        //            if (x.SaleRepresentative.LogoUpload.Contains("~"))
        //            {
        //                x.SaleRepresentative.LogoUpload = x.SaleRepresentative.LogoUpload.Replace('~', ' ');

        //                x.SaleRepresentative.LogoUpload.Trim();

        //                str = "<td><span>No Picture Found</span> / <a target='_blank' href=" + x.SaleRepresentative.LogoUpload + ">Logo</a> </td>";
        //            }
        //        }
        //        else if (x.SaleRepresentative.LogoUpload == null && x.SaleRepresentative.PictureUpload != null)
        //        {
        //            if (x.SaleRepresentative.PictureUpload.Contains("~"))
        //            {
        //                x.SaleRepresentative.PictureUpload = x.SaleRepresentative.PictureUpload.Replace('~', ' ');

        //                x.SaleRepresentative.PictureUpload.Trim();

        //                str = "<td> <a target='_blank' href=" + x.SaleRepresentative.PictureUpload + ">Picture</a> / <span>No Logo Found</span> </td>";
        //            }
        //        }
        //        else if (x.SaleRepresentative.LogoUpload != null && x.SaleRepresentative.PictureUpload != null)
        //        {
        //            if (x.SaleRepresentative.PictureUpload.Contains("~") || x.SaleRepresentative.LogoUpload.Contains("~"))
        //            {
        //                x.SaleRepresentative.PictureUpload = x.SaleRepresentative.PictureUpload.Replace('~', ' ');
        //                x.SaleRepresentative.LogoUpload = x.SaleRepresentative.LogoUpload.Replace('~', ' ');

        //                x.SaleRepresentative.PictureUpload.Trim();
        //                x.SaleRepresentative.LogoUpload.Trim();

        //                str = "<td> <a target='_blank' href=" + x.SaleRepresentative.PictureUpload + ">Picture</a> / <a target='_blank' href=" + x.SaleRepresentative.LogoUpload + ">Logo</a> </td>";
        //            }
        //        }
        //        else
        //        {
        //            str = "No Logo and No Image";
        //        }

        //        Company_SaleRep corpDTO = new Company_SaleRep()
        //        {
        //            Id = x.Id,
        //            //Name = x.SaleRepresentative.Name,
        //            //SalesFirmName = x.SaleRepresentative.SalesFirmName,
        //            //Email = x.SaleRepresentative.Email,
        //            //EmailReceiveLeads = x.SaleRepresentative.EmailReceiveLeads,
        //            //PictureUpload = x.SaleRepresentative.PictureUpload,
        //            //LogoUpload = x.SaleRepresentative.LogoUpload,
        //            CompanyId = x.CompanyId,
        //            SaleRepId = x.SaleRepId,
        //            IsActive = x.IsActive,
        //            Creadted_At = x.Creadted_At
        //        };

        //        co_rp_list.Add(corpDTO);
        //        ViewBag.salerep = co_rp_list;
        //    }
        //    return View();
        //}




        public ActionResult AddSaleRep(string err = "", string msg = "")
        {
            if (sessiondto.getRole() != 10)
            {
                return RedirectToAction("Login", "Auth");
            }

            List<State> states = new AdminBL().getStateList();
            int statescount = states.Count();

            ViewBag.statescount = statescount;
            ViewBag.states = states;
            ViewBag.Message = msg;
            ViewBag.Error = err;
            ViewBag.sts = states;
            return View();
        }

        [HttpPost]
        public ActionResult PostSaleRep(FormCollection form)
        {
            if (sessiondto.getRole() != 10)
            {
                return RedirectToAction("Login", "Auth");
            }

            SaleRepresentative sr = new SaleRepresentative()
            {
                Name = Request.Form["Name"],
                SalesFirmName = Request.Form["SalesFirmName"],
                Email = Request.Form["Email"],
                EmailReceiveLeads = Request.Form["EmailReceiveLeads"],
                Creadted_At = DateTime.Now,
                IsActive = 1
            };

            sr.PictureUpload = null;
            sr.LogoUpload = null;
            var file = Request.Files[0];
            var file1 = Request.Files[1];
            if (file.ContentLength > 0)
            {
                Directory.CreateDirectory(Server.MapPath("~") + "Content\\SalesRepImages\\");
                string relativePath = "~/Content/SalesRepImages/" + Path.GetFileName(file.FileName);
                string path = Path.Combine(Server.MapPath(relativePath));
                file.SaveAs(path);
                sr.PictureUpload = relativePath;
            }

            if (file1.ContentLength > 0)
            {
                Directory.CreateDirectory(Server.MapPath("~") + "Content\\SalesRepImages\\");
                string relativePath1 = "~/Content/SalesRepImages/" + Path.GetFileName(file1.FileName);
                string path1 = Path.Combine(Server.MapPath(relativePath1));
                file1.SaveAs(path1);
                sr.LogoUpload = relativePath1;
            }

            bool x = new AdminBL().AddSaleRepresentative(sr);
            if (x)
            {
                for (int i = 0; i <= Convert.ToInt32(Request.Form["count"]); i++)
                {
                    if (Request.Form["StateCover"] != null)
                    {
                        repStatePart(sr.Id, Convert.ToInt32(Request.Form["StateCover"]) + i);
                    }
                }
                //for (int i = 0; i <= Convert.ToInt32(Request.Form["count"]); i++)
                //{
                //    if (Request.Form["StateCover" + i.ToString()] != null)
                //    {
                //        if (Request.Form["PartofState" + i.ToString() + "_1"] == "All")
                //        {
                //            //for (int j = 0; j < 5; j++)
                //            //{
                //            //    repStatePart(sr.Id, Convert.ToInt32(Request.Form["StateCover" + i.ToString()]) + j);
                //            //}  
                //            repStatePart(sr.Id, Convert.ToInt32(Request.Form["StateCover" + i.ToString()]));
                //        }
                //        if (Request.Form["PartofState" + i.ToString() + "_2"] == "East")
                //        {
                //            repStatePart(sr.Id, Convert.ToInt32(Request.Form["StateCover" + i.ToString()]) + 1);
                //        }
                //        if (Request.Form["PartofState" + i.ToString() + "_3"] == "West")
                //        {
                //            repStatePart(sr.Id, Convert.ToInt32(Request.Form["StateCover" + i.ToString()]) + 2);
                //        }
                //        if (Request.Form["PartofState" + i.ToString() + "_4"] == "North")
                //        {
                //            repStatePart(sr.Id, Convert.ToInt32(Request.Form["StateCover" + i.ToString()]) + 3);
                //        }
                //        if (Request.Form["PartofState" + i.ToString() + "_5"] == "South")
                //        {
                //            repStatePart(sr.Id, Convert.ToInt32(Request.Form["StateCover" + i.ToString()]) + 4);
                //        }
                //        if (Request.Form["PartofState" + i.ToString() + "_6"] == "Metro")
                //        {
                //            repStatePart(sr.Id, Convert.ToInt32(Request.Form["StateCover" + i.ToString()]) + 5);
                //        }
                //    }
                //}

                Company_SaleRep cs = new Company_SaleRep()
                {
                    IsActive = 1,
                    CompanyId = sessiondto.getId(),
                    SaleRepId = sr.Id,
                    Creadted_At = DateTime.Now
                };
                new AdminBL().AddCompany_SaleRep(cs);

                return RedirectToAction("AddSaleRep", new { msg = "Sales representative successfully added." });
            }

Direct2Rep/Views/Company/AddCampaign.cshtml
@{
    ViewBag.Title = "AddCampaign";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-content-wrapper">
    <!-- BEGIN CONTENT BODY -->
    <div class="page-content">
        <!-- BEGIN PAGE HEAD-->
        <div class="page-head">
            <!-- BEGIN PAGE TITLE -->
            <div class="page-title">
                <h1>
                    Dashboard
                    <small>statistics, charts and reports</small>
                </h1>
            </div>
            <!-- END PAGE TITLE -->
        </div>
        <!-- END PAGE HEAD-->
        <!-- BEGIN PAGE BREADCRUMB -->
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <a href="@Url.Action("Index","Admin")">Home</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <span class="active">Add Campaign</span>
            </li>
        </ul>
        <!-- END PAGE BREADCRUMB -->
        <!-- BEGIN PAGE BASE CONTENT -->
        <div class="row">
            <div class="col-md-12">
                <div class="row">
                    @if (ViewBag.Message != "")
                    {
                        <div class="alert alert-success">
                            @ViewBag.Message
                        </div>
                    }
                    @if (ViewBag.Error != "")
                    {
                        <div class="alert alert-danger">
                            @ViewBag.Error
                        </div>
                    }
                </div>
                <!-- BEGIN SAMPLE FORM PORTLET-->
                <div class="portlet light bordered">
                    <div class="portlet-title">
                        <div class="caption font-green-haze">
                            <i class="icon-home font-green-haze"></i>
                            <span class="caption-subject bold uppercase"> Add New Campaign</span>
                        </div>
                        <div class="actions">

                            <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                        </div>
                    </div>
                    <div class="portlet-body form">
                        <form role="form" class="form-horizontal" action="@Url.Action("PostCampaign","Company")" method="post" enctype="multipart/form-data">
                            <div class="form-body">

                                <div class="form-group form-md-line-input">
                                    <label class="col-md-2 control-label" for="form_control_1">Campaign Name</label>
                                    <div class="col-md-10">
                                        <input type="text" class="form-control" id="name" name="Name" onchange="ValidateName()" placeholder="Enter name" required>
                                        <div class="form-control-focus"> </div>
                                    </div>
                                    <label class="col-md-offset-2 control-label" id="msg" style="color: cornflowerblue;"></label>

                                </div>

                                <div class="form-group form-md-line-input">
                                    <label class="col-md-2 control-label" for="form_control_1"><button id="myBtn" class="btn btn-info btn-sm" onclick="GenerateUrl()" type="button">Generate Campaign Link</button></label>

                                    <div class="col-md-10">
                                            <input type="hidden" class="form-control" id="url1" name="Url">
                                       <a id="url" href=""></a>
                                            <div class="form-control-focus"> </div>                                       
                                    </div>
                                    <label class="col-md-offset-2 control-label" id="msg1" style="color: cornflowerblue;"></label>
                                </div>

                                <div class="form-actions">
                                    <div class="row">
                                        <div class="col-md-offset-2 col-md-10">
                                            <button type="submit" class="btn blue">Done</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.2.1.min.js"></script>
<script>

    function GenerateUrl() {
        var name = document.getElementById('name').value;
        $.ajax({
            dataType: "json",
            type: "GET",
            url: '../Company/GenerateUrl',
            data: { campaignname: name },
            //traditional: true,
            success: function (response) {

                if (response == "")
                {
                    $("#msg").html("Url cannot be generated for this name of the campaign. Please enter another name.");
                    $("#msg").addClass("text-danger");
                    $(':input[type="submit"]').prop('disabled', true);
                }
                else
                {
                    $('#url1').val(response);
                    $('#url').attr('href', response);
                    $('#url').attr('target', '_blank');
                    $('#url').html(response);
                    $("#myBtn").prop("disabled", true);
                }
                
            },
            error: function (response) {
                alert('Error');
            }
        });
    }


        function ValidateName() {
        var campaignname = document.getElementById('name').value;
        $.ajax({
            dataType: "json",
            type: "POST",
            url: '../Company/validateCampaignName',
            data: { Name: campaignname },
            //traditional: true,
            success: function (response) {
                if (response == 0)
                {
                    $("#msg").html("Campaign having this name already exist. Please enter a new campaign name.");
                    $("#msg").addClass("text-danger");
                    $(':input[type="submit"]').prop('disabled', true);
                    $("#myBtn").prop("disabled", true);
                }
                else if (response == 2)
                {
                    $("#msg").html("Please enter a new valid name.");
                    $("#msg").addClass("text-danger");
                    $(':input[type="submit"]').prop('disabled', true);
                    $("#myBtn").prop("disabled", true);
                }
                else
                {
                    $("#msg").removeClass("text-danger");
                    $("#msg").addClass("text-success");
                    $("#msg").html("Campaign name is available.");
                    $(':input[type="submit"]').prop('disabled', false);
                    $("#myBtn").prop("disabled", false);
                }
            },
            error: function (response) {
                alert('Error');
            }
        });
    }
</script>

Direct2Rep/Views/Company/Campaign.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Campaign</title>
</head>
<body>
    <div>
        @ViewBag.company/@ViewBag.campaign
    </div>
</body>
</html>

Direct2Rep/Views/Company/EditCampaign.cshtml
@{
    ViewBag.Title = "EditCampaign";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@model Direct2Rep.Models.Campaign
<div class="page-content-wrapper">
    <!-- BEGIN CONTENT BODY -->
    <div class="page-content">
        <!-- BEGIN PAGE HEAD-->
        <div class="page-head">
            <!-- BEGIN PAGE TITLE -->
            <div class="page-title">
                <h1>
                    Dashboard
                    <small>statistics, charts and reports</small>
                </h1>
            </div>
            <!-- END PAGE TITLE -->
        </div>
        <!-- END PAGE HEAD-->
        <!-- BEGIN PAGE BREADCRUMB -->
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <a href="@Url.Action("Index","Admin")">Home</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <span class="active">Update Campaign</span>
            </li>
        </ul>
        <!-- END PAGE BREADCRUMB -->
        <!-- BEGIN PAGE BASE CONTENT -->
        <div class="row">
            <div class="col-md-12">
                <!-- BEGIN SAMPLE FORM PORTLET-->
                <div class="portlet light bordered">
                    <div class="portlet-title">
                        <div class="caption font-green-haze">
                            <i class="icon-home font-green-haze"></i>
                            <span class="caption-subject bold uppercase"> Update Campaign</span>
                        </div>
                        <div class="actions">

                            <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                        </div>
                    </div>
                    <div class="portlet-body form">
                        <div class="row">
                            @if (ViewBag.Message != null)
                            {
                                <div class="alert alert-success">
                                    @ViewBag.Message
                                </div>
                            }
                            @if (ViewBag.Error != null)
                            {
                                <div class="alert alert-danger">
                                    @ViewBag.Error
                                </div>
                            }
                        </div>
                        <form role="form" class="form-horizontal" action="@Url.Action("UpdateCampaign","Company")" method="post" enctype="multipart/form-data">
                            <div class="form-body">
                                <input type="hidden" name="Id" value="@Model.Id">
                                <div class="form-group form-md-line-input">
                                    <label class="col-md-2 control-label" for="form_control_1">Campaign Name</label>
                                    <div class="col-md-10">
                                        <input type="text" name="Name" class="form-control" id="form_control_1" value="@Model.Name" required>
                                        <div class="form-control-focus"> </div>
                                    </div>
                                </div>
                                <div class="form-group form-md-line-input">
                                    <label class="col-md-2 control-label" for="form_control_1">Campaign Url</label>
                                    <div class="col-md-10">
                                        <input type="text" name="Url" class="form-control" id="url" onchange="ValidateUrl()" value="@Model.Url" readonly>
                                        <div class="form-control-focus"> </div>
                                    </div>
                                    <label class="col-md-offset-2 control-label" id="msg" style="color: cornflowerblue;"></label>

                                </div>
                                <div class="form-actions">
                                    <div class="row">
                                        <div class="col-md-offset-2 col-md-10">
                                            <button type="submit" class="btn blue">Update</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Direct2Rep/Views/Company/ListCampaigns.cshtml
@{
    ViewBag.Title = "ListCampaigns";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@model List<Direct2Rep.Models.Campaign>
@using Direct2Rep.Models
@using Direct2Rep.Helping_Classes
<div class="page-content-wrapper">
    <!-- BEGIN CONTENT BODY -->
    <div class="page-content">
        <!-- BEGIN PAGE HEAD-->
        <div class="page-head">
            <!-- BEGIN PAGE TITLE -->
            <div class="page-title">
                <h1>
                    Dashboard
                    <small>statistics, charts and reports</small>
                </h1>
            </div>
            <!-- END PAGE TITLE -->
        </div>
        <!-- END PAGE HEAD-->
        <!-- BEGIN PAGE BREADCRUMB -->
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <a href="@Url.Action("Index","Admin")">Home</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <span class="active">Campaigns</span>
            </li>
        </ul>
        <!-- END PAGE BREADCRUMB -->
        <!-- BEGIN PAGE BASE CONTENT -->
        <div class="row">
            <div class="col-md-12">
                <!-- BEGIN EXAMPLE TABLE PORTLET-->
                <div class="portlet light bordered">
                    <div class="portlet-title">
                        <div class="caption font-dark">
                            <i class=" font-dark"></i>
                            <span class="caption-subject bold uppercase">List of Campaigns</span>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <table class="table table-striped table-bordered table-hover" id="sample_1">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Created At</th>
                                    <th>Url</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.Name</td>
                                        @*@{ 
                                            if(item.Url)
                                            {

                                            }
                                            string url = "http://" + item.Url;
                                        }*@
                                        <td>@item.Creadted_At</td>
                                        <td><a href="@item.Url" target="_blank">@item.Url</a></td>
                                        <td>
                                            <a class="btn btn-info" href="@Url.Action("EditCampaign","Company",new { Id = StringCipher.Base64Encode(item.Id.ToString()) })">
                                                EDIT
                                            </a>
                                            <a class="btn btn-danger" data-target="#deleteCampaign" data-toggle="modal" onclick="deleteCampaign('@item.Id')">
                                                DELETE
                                            </a>

                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- END EXAMPLE TABLE PORTLET-->
            </div>
        </div>
        <!-- END PAGE BASE CONTENT -->
    </div>
    <!-- END CONTENT BODY -->
</div>
<div class="modal fade" id="deleteCampaign" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <form action="@Url.Action("DeleteCampaign","Company")" method="post">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="exampleModalLabel">Delete</h4>
                </div>
                <div class="modal-body">
                    <p>You are going to delete this Campaign. Are you sure?</p>
                    <input type="hidden" class="form-control" id="propId" name="Id" required>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                        <button type="submit" class="btn btn-primary">Yes</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script>
    function deleteCampaign(Id) {
        $('#propId').val(Id);
    }
</script>